use_frameworks!
platform :ios, '9.0'

target 'AESStream_Example' do
  pod 'AESStream', :path => '../'
  pod 'SwiftLint'
end

target 'AESStream_Tests' do
    inherit! :search_paths
    pod 'AESStream', :path => '../'
    pod 'CleanTests', :git => 'https://github.com/igorkotkovets/pod.swift.clean-tests.git'

end
